# Generated by Django 5.0 on 2023-12-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VectorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='楼栋名称')),
                ('describe', models.CharField(max_length=64, verbose_name='楼栋描述')),
                ('minHeight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('maxHeight', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
