# Generated by Django 5.0 on 2023-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorinfo',
            name='describe',
            field=models.CharField(max_length=64, null=True, verbose_name='楼栋描述'),
        ),
    ]
