# Generated by Django 5.0 on 2023-12-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0003_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
