# Generated by Django 5.0 on 2023-12-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0004_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorinfo',
            name='latitude',
            field=models.DecimalField(decimal_places=26, default=29.867756387322657, max_digits=28),
        ),
        migrations.AddField(
            model_name='vectorinfo',
            name='longitude',
            field=models.DecimalField(decimal_places=25, default=114.26617983264441, max_digits=28),
        ),
    ]
