# Generated by Django 5.0 on 2023-12-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0005_vectorinfo_latitude_vectorinfo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorinfo',
            name='latitude',
            field=models.DecimalField(decimal_places=26, max_digits=28, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='vectorinfo',
            name='longitude',
            field=models.DecimalField(decimal_places=25, max_digits=28, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='vectorinfo',
            name='maxHeight',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='最大高度'),
        ),
        migrations.AlterField(
            model_name='vectorinfo',
            name='minHeight',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='最小高度'),
        ),
    ]
