# Generated by Django 5.0 on 2023-12-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0006_alter_vectorinfo_latitude_alter_vectorinfo_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorinfo',
            name='latitude',
            field=models.DecimalField(decimal_places=26, max_digits=28, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='vectorinfo',
            name='longitude',
            field=models.DecimalField(decimal_places=25, max_digits=28, null=True, verbose_name='经度'),
        ),
    ]
