# Generated by Django 5.0 on 2023-12-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0007_alter_vectorinfo_latitude_alter_vectorinfo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorinfo',
            name='cartX',
            field=models.DecimalField(decimal_places=13, max_digits=16, null=True, verbose_name='笛卡尔坐标X'),
        ),
        migrations.AddField(
            model_name='vectorinfo',
            name='cartY',
            field=models.DecimalField(decimal_places=13, max_digits=16, null=True, verbose_name='笛卡尔坐标Y'),
        ),
    ]
