# Generated by Django 5.0 on 2023-12-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0008_vectorinfo_cartx_vectorinfo_carty'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorinfo',
            name='cartZ',
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True, verbose_name='笛卡尔坐标Y'),
        ),
        migrations.AlterField(
            model_name='vectorinfo',
            name='cartX',
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True, verbose_name='笛卡尔坐标X'),
        ),
        migrations.AlterField(
            model_name='vectorinfo',
            name='cartY',
            field=models.DecimalField(decimal_places=9, max_digits=16, null=True, verbose_name='笛卡尔坐标Y'),
        ),
    ]
