# Generated by Django 5.0 on 2023-12-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0009_vectorinfo_cartz_alter_vectorinfo_cartx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='房间名称')),
                ('camera', models.IntegerField(verbose_name='摄像头组')),
                ('buildId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vectorInfo.vectorinfo', verbose_name='楼栋id')),
            ],
        ),
    ]
