# Generated by Django 5.0 on 2023-12-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0010_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='buildId',
            new_name='build',
        ),
        migrations.RemoveField(
            model_name='room',
            name='camera',
        ),
    ]
