# Generated by Django 5.0 on 2023-12-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0012_room_storey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='storey',
            field=models.IntegerField(verbose_name='楼层'),
        ),
    ]
