# Generated by Django 5.0 on 2024-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0013_alter_room_storey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='监控名称')),
                ('describe', models.CharField(max_length=64, null=True, verbose_name='监控描述')),
                ('url', models.CharField(max_length=64, verbose_name='监控地址')),
                ('cameraCartX', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='相机笛卡尔坐标X')),
                ('cameraCartY', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='相机笛卡尔坐标Y')),
                ('cameraCartZ', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='相机笛卡尔坐标Y')),
                ('positionCartX', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='目标点笛卡尔坐标X')),
                ('positionCartY', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='目标点笛卡尔坐标Y')),
                ('positionCartZ', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='目标点笛卡尔坐标Y')),
                ('fov', models.IntegerField(verbose_name='视角大小')),
                ('aspectRatio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='视角比例')),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='透明度')),
            ],
        ),
    ]
