# Generated by Django 5.0 on 2024-01-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0014_monitorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorinfo',
            name='cameraCartX',
            field=models.CharField(max_length=64, verbose_name='相机笛卡尔坐标X'),
        ),
        migrations.AlterField(
            model_name='monitorinfo',
            name='cameraCartY',
            field=models.CharField(max_length=64, verbose_name='相机笛卡尔坐标Y'),
        ),
        migrations.AlterField(
            model_name='monitorinfo',
            name='cameraCartZ',
            field=models.CharField(max_length=64, verbose_name='相机笛卡尔坐标Y'),
        ),
        migrations.AlterField(
            model_name='monitorinfo',
            name='positionCartX',
            field=models.CharField(max_length=64, verbose_name='目标点笛卡尔坐标X'),
        ),
        migrations.AlterField(
            model_name='monitorinfo',
            name='positionCartY',
            field=models.CharField(max_length=64, verbose_name='目标点笛卡尔坐标Y'),
        ),
        migrations.AlterField(
            model_name='monitorinfo',
            name='positionCartZ',
            field=models.CharField(max_length=64, verbose_name='目标点笛卡尔坐标Y'),
        ),
    ]
