# Generated by Django 5.0 on 2024-01-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorInfo', '0015_alter_monitorinfo_cameracartx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorinfo',
            name='far',
            field=models.IntegerField(default=100, verbose_name='视角大小'),
        ),
    ]
